//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Andradion 2.rc
//
#define IDS_DEFAULTNAME                 1
#define IDS_SELECTCHARACTERCAPTION      1
#define IDS_DIFFICULTYLEVEL1            2
#define IDS_DIFFICULTYLEVEL2            3
#define IDS_DIFFICULTYLEVEL3            4
#define IDS_CHARNAME1                   5
#define IDS_CHARNAME2                   6
#define IDS_CHARNAME3                   7
#define IDS_CHARNAME4                   8
#define IDS_CHARNAME5                   9
#define IDS_CHARNAME6                   10
#define IDS_CHARNAME7                   11
#define IDS_CHARNAME8                   12
#define IDS_CHARNAME9                   13
#define IDS_UNAVAILABLELEVEL            14
#define IDS_MAGICWORD                   15
#define IDS_WINDOWCAPTION               16
#define IDS_WINDOWCLASS                 17
#define IDS_OLDDX                       18
#define IDS_HOLDPBUTTON                 19
#define IDS_FORCEPICKUPSP               19
#define IDS_NEWPLAYER                   20
#define IDS_OLDPLAYER                   21
#define IDS_HOLDPBUTTONMP               22
#define IDS_FORCEPICKUPMP               22
#define IDS_NORECORDS                   23
#define IDS_NODLL                       24
#define IDS_PAUSE                       25
#define IDS_BESTTIMEFORMAT              26
#define IDS_BESTSCOREFORMAT             27
#define IDS_RECORDSUMMARY               28
#define IDS_MAXSCORE                    29
#define IDI_APPICON                     102
#define IDS_INIFILE                     110
#define IDS_MAINMENUITEM1               111
#define IDS_MAINMENUITEM2               112
#define IDS_MAINMENUITEM3               113
#define IDS_MAINMENUCAPTION             114
#define IDS_LEVELSELECTCAPTION          115
#define IDS_DIFFICULTYSELECTCAPTION     116
#define IDS_CONFIRMATIONCAPTION         117
#define IDS_NO                          118
#define IDS_YES                         119
#define IDS_SELECTCONNECTIONMETHODCAPTION 120
#define IDS_ENTERNAMECAPTION            121
#define IDS_SELECTGAMECAPTION           122
#define IDS_GAMESLOTNAME1               123
#define IDS_GAMESLOTNAME2               124
#define IDS_GAMESLOTNAME3               125
#define IDS_GAMESLOTNAME4               126
#define IDS_GAMESLOTNAME5               127
#define IDS_GAMESLOTNAME6               128
#define IDS_GAMESLOTNAME7               129
#define IDS_GAMESLOTNAME8               130
#define IDS_GAMESLOTNAME9               131
#define IDS_GAMESLOTNAME10              132
#define IDS_COULDNOTCONNECT             133
#define IDS_GAMESLOTNAME11              133
#define IDS_GAMESLOTNAME12              134
#define IDS_LEVELPATH                   143
#define IDS_NOCONNECTIONMETHODAVAILABLE 144
#define IDS_GUARANTEEDMSGON             153
#define IDS_GUARANTEEDMSGOFF            154
#define IDS_KILLEDYOURSELF              155
#define IDS_KILLED                      156
#define IDS_YOU                         157
#define IDS_YOUKILLED                   158
#define IDS_KILLEDTHEMSELVES            159
#define IDS_SPKILLED                    160
#define IDS_INVALIDSYNCRATE             161
#define IDS_BUDGETCUTS                  201
#define IDS_LEVELNAME1                  202
#define IDS_LEVELFILE1                  203
#define IDS_STRING204                   204
#define IDS_STRING205                   205
#define IDB_TURNER                      206
#define IDS_STRING206                   206
#define IDB_STORY                       207
#define IDS_STRING207                   207
#define IDS_STRING208                   208
#define IDD_CFG                         209
#define IDS_STRING209                   209
#define IDS_STRING210                   210
#define IDS_STRING211                   211
#define IDS_STRING212                   212
#define IDS_STRING213                   213
#define IDS_STRING214                   214
#define IDS_STRING215                   215
#define IDS_STRING216                   216
#define IDS_STRING217                   217
#define IDS_STRING218                   218
#define IDS_STRING219                   219
#define IDS_STRING220                   220
#define IDS_STRING221                   221
#define IDS_STRING222                   222
#define IDS_STRING223                   223
#define IDS_STRING224                   224
#define IDS_STRING225                   225

#define IDR_INTROMUSIC                  279
#define IDR_MENUMUSIC                   281
#define IDR_YOUWINTUNE                       283
#define IDR_MIDI2                       284
#define IDR_MIDI3                       285
#define IDR_MIDI4                       286
#define IDB_BITMAP1                     293
#define IDB_BITMAP2                     294
#define IDB_BITMAP3                     295
#define IDB_BITMAP4                     296
#define IDB_BITMAP5                     297
#define IDB_BITMAP6                     298
#define IDB_BITMAP7                     299
#define IDB_BITMAP8                     300
#define IDB_BITMAP9                     301
#define IDB_BITMAP10                    302
#define IDB_BITMAP11                    303
#define IDB_BITMAP12                    304
#define IDB_BITMAP13                    305
#define IDB_BITMAP14                    306
#define IDB_BITMAP15                    307
#define IDB_BITMAP16                    308
#define IDB_BITMAP17                    309
#define IDB_BITMAP18                    310
#define IDB_BITMAP19                    311
#define IDB_BITMAP20                    312
#define IDB_BITMAP21                    313
#define IDB_BITMAP22                    314
#define IDB_BITMAP23                    315
#define IDB_BITMAP24                    316
#define IDB_BITMAP25                    317
#define IDB_BITMAP26                    318
#define IDB_BITMAP27                    319
#define IDB_BITMAP28                    320
#define IDB_BITMAP29                    321
#define IDB_BITMAP30                    322
#define IDB_BITMAP31                    323
#define IDB_BITMAP32                    324
#define IDB_BITMAP33                    325
#define IDB_BITMAP34                    326
#define IDB_BITMAP35                    327
#define IDB_BITMAP36                    328
#define IDB_BITMAP37                    329
#define IDB_BITMAP38                    330
#define IDB_BITMAP39                    331
#define IDB_BITMAP40                    332
#define IDB_BITMAP41                    333
#define IDB_BITMAP42                    334
#define IDB_BITMAP43                    335
#define IDB_BITMAP44                    336
#define IDB_BITMAP45                    337
#define IDB_BITMAP46                    338
#define IDB_BITMAP47                    339
#define IDB_BITMAP48                    340
#define IDB_BITMAP49                    341
#define IDB_BITMAP50                    342
#define IDB_BITMAP51                    343
#define IDB_BITMAP52                    344
#define IDB_BITMAP53                    345
#define IDB_BITMAP54                    346
#define IDB_BITMAP55                    347
#define IDB_BITMAP56                    348
#define IDB_BITMAP57                    349
#define IDB_BITMAP58                    350
#define IDB_BITMAP59                    351
#define IDB_BITMAP60                    352
#define IDB_BITMAP61                    353
#define IDB_BITMAP62                    354
#define IDB_BITMAP63                    355
#define IDB_BITMAP64                    356
#define IDB_BITMAP65                    357
#define IDB_BITMAP66                    358
#define IDB_BITMAP67                    359
#define IDB_BITMAP68                    360
#define IDB_BITMAP69                    361
#define IDB_BITMAP70                    362
#define IDB_BITMAP71                    363
#define IDB_BITMAP72                    364
#define IDB_BITMAP73                    365
#define IDB_BITMAP74                    366
#define IDB_BITMAP75                    367
#define IDB_BITMAP76                    368
#define IDB_BITMAP77                    369
#define IDB_BITMAP78                    370
#define IDB_BITMAP79                    371
#define IDB_BITMAP80                    372
#define IDB_BITMAP81                    373
#define IDB_BITMAP82                    374
#define IDB_BITMAP83                    375
#define IDB_BITMAP84                    376
#define IDB_BITMAP85                    377
#define IDB_BITMAP86                    378
#define IDB_BITMAP87                    379
#define IDB_BITMAP88                    380
#define IDB_BITMAP89                    381
#define IDB_BITMAP90                    382
#define IDB_BITMAP91                    383
#define IDB_BITMAP92                    384
#define IDB_TITLETURN                   395
#define IDR_WELCOMEBOXMUSIC             397
#define IDR_LIGHTRAIN                   400
#define IDR_HEAVYRAIN                   401
#define IDR_CRICKETS                    402
#define IDR_THUNDER1                    403
#define IDR_THUNDER2                    404
#define IDR_THUNDER3                    405
#define IDB_BACKGROUND                  415
#define IDR_SPLASH                      416
#define IDR_FONT                        428
#define IDC_FPSF                        1000
#define IDC_SYNC                        1000
#define IDLAUNCH                        1001
#define IDQUIT                          1002
#define IDLAUNCHWITHOUTMUSIC            1005

// resources used only by the level maker
#define IDC_TURNER                      1112
#define IDC_SALLY                       1113
#define IDC_PISTOL                      1114
#define IDC_MILTON                      1115
#define IDC_MACHINEGUN                  1116
#define IDC_HEALTH                      1117
#define IDC_BAZOOKA                     1118
#define IDC_EVILTURNER                  1119
#define IDB_GENERICHEALTH               1120
#define IDB_GENERICMILTON               1121
#define IDB_GENERICSALLY                1122
#define IDB_GENERICTURNER               1123
#define IDB_GENERICBAZOOKA              1124
#define IDB_GENERICEVILTURNER           1125
#define IDB_GENERICMACHINEGUN           1126
#define IDB_GENERICPISTOL               1127

