c:
cd\andrad~2
cd resource
wav2raw aliendeath1.snd aliendeath1.wav
wav2raw aliendeath2.snd aliendeath2.wav
wav2raw aliendeath3.snd aliendeath3.wav
wav2raw alienhit1.snd alienhit1.wav
wav2raw alienhit2.snd alienhit2.wav
wav2raw alienhit3.snd alienhit3.wav
wav2raw bazooka.snd bazooka.wav
wav2raw bing.snd bing.wav
wav2raw charmindeath.snd charmindeath.wav
wav2raw charminhit1.snd charminhit1.wav
wav2raw charminhit2.snd charminhit2.wav
wav2raw charminhit3.snd charminhit3.wav
wav2raw cokedeath.snd cokedeath.wav
wav2raw cokehit1.snd cokehit1.wav
wav2raw cokehit2.snd cokehit2.wav
wav2raw cokehit3.snd cokehit3.wav
wav2raw crickets.snd crickets.wav
wav2raw gunnoise.snd gunnoise.wav
wav2raw heavyrain.snd heavyrain.wav
wav2raw koolaidedeath.snd koolaidedeath.wav
wav2raw koolaidehit1.snd koolaidehit1.wav
wav2raw koolaidehit2.snd koolaidehit2.wav
wav2raw koolaidehit3.snd koolaidehit3.wav
wav2raw lightrain.snd lightrain.wav
wav2raw machinegun.snd machinegun.wav
wav2raw okgotit.snd okgotit.wav
wav2raw pepsideath.snd pepsideath.wav
wav2raw pepsihit1.snd pepsihit1.wav
wav2raw pepsihit2.snd pepsihit2.wav
wav2raw pepsihit3.snd pepsihit3.wav
wav2raw pistol.snd pistol.wav
wav2raw pow.snd pow.wav
wav2raw step.snd step.wav
wav2raw switzdeath.snd switzdeath.wav
wav2raw switzhit1.snd switzhit1.wav
wav2raw switzhit2.snd switzhit2.wav
wav2raw switzhit3.snd switzhit3.wav
wav2raw thunder1.snd thunder1.wav
wav2raw thunder2.snd thunder2.wav
wav2raw thunder3.snd thunder3.wav
wav2raw turnerdeath.snd turnerdeath.wav
wav2raw turnerhit1.snd turnerhit1.wav
wav2raw turnerhit2.snd turnerhit2.wav
wav2raw turnerhit3.snd turnerhit3.wav
wav2raw wammo.snd wammo.wav
wav2raw warpout.snd warpout.wav
wav2raw zap.snd zap.wav

